
         angular.module("App", []).controller("AlphaController", function($scope) {
		 
		 var vm = $scope;
		 
		 vm.records = [];
		 vm.reverse = false;
		 
		 //////////////////////////
		 //Toggle ordering of table
		 vm.reverseOrder = function(sortFor) {
		 
		 vm.sortFor = sortFor;
		 vm.reverse = (vm.reverse == false) ? true : false;
		 
		 }
	 
		 //////////////////////////
		 //Generate numbers to populate table
		 //The klass value is specified through the "add row" buttons. 
		 //The value is recorded into the item object
		 vm.getNumbers = function(klass) {
		 		
		  var item = { 
		 
		    "number"     : Math.trunc((Math.random() * 100) + 1),
			"decimal"    : ((Math.random() * 100) + 1),
			"negative"   : Math.trunc(((Math.random() * 100) + 1) * -1),
			"colorClass" : klass
			
			}
			
		  //Append to array, 'item'
		  vm.records.push(item);
		  //Limit the number of records generated by checking length of array
		  if (vm.records.length < 5) {
		   vm.getNumbers();  
		  }
		  
		  else return;
		 
		 }
		 
		//////////////////////////
		vm.providedNumbers = function(klass, number, decimal, negative) {
		
		var item = { 
		 
		    "number"     : number,
			"decimal"    : decimal,
			"negative"   : negative,
			"colorClass" : klass
			
			}
			
		  //Append to array, 'item'
		  vm.records.push(item);
		  
		  return;
		
		 }});
